/**
 * buildInlineAssets.mjs
 *
 * Run before `next build` to inline all component-library fonts and CSS
 * as TypeScript string constants. This ensures the assets survive Railway's
 * Next.js standalone build, which does not copy src/ files into the output.
 *
 * Usage: node src/lib/component-library/buildInlineAssets.mjs
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const fontsDir = path.join(__dirname, "fonts");
const cssDir = __dirname; // layouts.css and fonts.css are in the component-library root
const outFile = path.join(__dirname, "inlinedAssets.ts");

// ── 1. Inline all woff2 fonts as base64 data URIs ─────────────────────────

const fontFiles = fs.readdirSync(fontsDir).filter((f) => f.endsWith(".woff2"));

const fontEntries = fontFiles.map((filename) => {
  const filePath = path.join(fontsDir, filename);
  const base64 = fs.readFileSync(filePath).toString("base64");
  const dataUri = `data:font/woff2;base64,${base64}`;
  return `  "${filename}": "${dataUri}"`;
});

// ── 2. Inline layouts.css and fonts.css as strings ────────────────────────

const layoutsCss = fs.readFileSync(path.join(cssDir, "layouts.css"), "utf8");

// Build fonts.css with base64 data URIs replacing the url("../fonts/...") references
let fontsCss = fs.readFileSync(path.join(cssDir, "fonts.css"), "utf8");

for (const filename of fontFiles) {
  const filePath = path.join(fontsDir, filename);
  const base64 = fs.readFileSync(filePath).toString("base64");
  const dataUri = `data:font/woff2;base64,${base64}`;
  // Replace all occurrences of url("../fonts/<filename>") with the data URI
  fontsCss = fontsCss.replaceAll(
    `url("../fonts/${filename}")`,
    `url("${dataUri}")`
  );
}

// ── 3. Write inlinedAssets.ts ──────────────────────────────────────────────

const output = `/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by buildInlineAssets.mjs
 * All fonts are inlined as base64 data URIs so this module works in
 * Railway's Next.js standalone build without any file system access.
 */

/** Complete fonts.css with all @font-face src() replaced by base64 data URIs */
export const FONTS_CSS = ${JSON.stringify(fontsCss)};

/** Component layout CSS (brand-agnostic, uses CSS variables) */
export const LAYOUTS_CSS = ${JSON.stringify(layoutsCss)};

/** Map of filename → base64 data URI for individual font lookup if needed */
export const FONT_DATA_URIS: Record<string, string> = {
${fontEntries.join(",\n")},
};
`;

fs.writeFileSync(outFile, output, "utf8");

const fontCount = fontFiles.length;
const totalKb = Math.round(Buffer.byteLength(output, "utf8") / 1024);
console.log(
  `✓ inlinedAssets.ts written — ${fontCount} fonts, ${totalKb}KB total`
);
